def process_words(words):
    """Helper function to process word timings."""
    return [
        {
            "word": w["word"].lower().replace(r"[^\w\s]", "").strip(),
            "startTime": float(w.get("startOffset", "0s").replace("s", "")),
            "endTime": float(w.get("endOffset", "0s").replace("s", "")),
        }
        for w in words
    ]

song_refrains = {
    "aranha": {
      "time": 18,
      "language": "pt-BR",
      "text": "A dona aranha subiu pela parede\nVeio a chuva forte e a derrubou\nJá passou a chuva e o sol já vai surgindo\nE a dona aranha continua a subir",
      "words": process_words([
        {"startOffset": "0.800s", "endOffset": "1.200s", "word": "A"},
        {"startOffset": "1.240s", "endOffset": "1.680s", "word": "dona"},
        {"startOffset": "1.680s", "endOffset": "2.440s", "word": "aranha"},
        {"startOffset": "2.440s", "endOffset": "2.960s", "word": "subiu"},
        {"startOffset": "2.960s", "endOffset": "3.440s", "word": "pela"},
        {"startOffset": "3.440s", "endOffset": "4.440s", "word": "parede,"},
        {"startOffset": "4.760s", "endOffset": "5.080s", "word": "veio"},
        {"startOffset": "5.080s", "endOffset": "5.160s", "word": "a"},
        {"startOffset": "5.160s", "endOffset": "5.640s", "word": "chuva"},
        {"startOffset": "5.640s", "endOffset": "6.880s", "word": "forte"},
        {"startOffset": "6.880s", "endOffset": "7.040s", "word": "e"},
        {"startOffset": "7.040s", "endOffset": "7.160s", "word": "a"},
        {"startOffset": "7.160s", "endOffset": "7.960s", "word": "derrubou."},
        {"startOffset": "8.720s", "endOffset": "8.880s", "word": "Já"},
        {"startOffset": "8.880s", "endOffset": "9.480s", "word": "passou"},
        {"startOffset": "9.480s", "endOffset": "9.560s", "word": "a"},
        {"startOffset": "9.560s", "endOffset": "10.480s", "word": "chuva"},
        {"startOffset": "10.480s", "endOffset": "10.520s", "word": "e"},
        {"startOffset": "10.520s", "endOffset": "10.560s", "word": "o"},
        {"startOffset": "10.760s", "endOffset": "10.960s", "word": "sol"},
        {"startOffset": "10.960s", "endOffset": "11.160s", "word": "já"},
        {"startOffset": "11.160s", "endOffset": "11.360s", "word": "vai"},
        {"startOffset": "11.360s", "endOffset": "12.400s", "word": "surgindo"},
        {"startOffset": "12.800s", "endOffset": "13.040s", "word": "e"},
        {"startOffset": "13.040s", "endOffset": "13.160s", "word": "a"},
        {"startOffset": "13.160s", "endOffset": "13.600s", "word": "dona"},
        {"startOffset": "13.600s", "endOffset": "14.160s", "word": "aranha"},
        {"startOffset": "14.160s", "endOffset": "15.280s", "word": "continua"},
        {"startOffset": "15.280s", "endOffset": "15.400s", "word": "a"},
        {"startOffset": "15.400s", "endOffset": "16s", "word": "subir."},
      ]),
    },
    "atirei": {
      "time": 20,
      "language": "pt-BR",
      "text": "Atirei o pau no gato-to\nMas o gato-to, não morreu-reu-reu\nDona chica-ca admirou-se-se do miau\nDo miau que o gato deu - miau!",
      "words": process_words([
        {"startOffset": "1.240s", "endOffset": "2.520s", "word": "Atirei"},
        {"startOffset": "2.520s", "endOffset": "2.600s", "word": "o"},
        {"startOffset": "2.600s", "endOffset": "3s", "word": "pau"},
        {"startOffset": "3s", "endOffset": "3.160s", "word": "no"},
        {"startOffset": "3.160s", "endOffset": "4.200s", "word": "gato,"},
        {"startOffset": "4.240s", "endOffset": "4.640s", "word": "to,"},
        {"startOffset": "4.640s", "endOffset": "5.160s", "word": "mas"},
        {"startOffset": "5.160s", "endOffset": "5.280s", "word": "o"},
        {"startOffset": "5.280s", "endOffset": "6.320s", "word": "gato"},
        {"startOffset": "6.360s", "endOffset": "6.680s", "word": "to"},
        {"startOffset": "6.680s", "endOffset": "7.160s", "word": "não"},
        {"startOffset": "7.160s", "endOffset": "7.880s", "word": "morreu."},
        {"startOffset": "7.960s", "endOffset": "8.400s", "word": "reu,"},
        {"startOffset": "8.440s", "endOffset": "8.960s", "word": "reu"},
        {"startOffset": "9s", "endOffset": "9.440s", "word": "Dona"},
        {"startOffset": "9.920s", "endOffset": "10.220s", "word": "Chica"},
        {"startOffset": "10.220s", "endOffset": "10.320s", "word": "ca"},
        {"startOffset": "10.920s", "endOffset": "11.920s", "word": "admirou"},
        {"startOffset": "12.200s", "endOffset": "12.320s", "word": "se"},
        {"startOffset": "12.320s", "endOffset": "12.400s", "word": "se"},
        {"startOffset": "13.160s", "endOffset": "13.480s", "word": "Do"},
        {"startOffset": "13.480s", "endOffset": "14.200s", "word": "miau,"},
        {"startOffset": "14.240s", "endOffset": "14.560s", "word": "do"},
        {"startOffset": "14.560s", "endOffset": "15s", "word": "miau"},
        {"startOffset": "15s", "endOffset": "15.200s", "word": "que"},
        {"startOffset": "15.200s", "endOffset": "15.280s", "word": "o"},
        {"startOffset": "15.280s", "endOffset": "15.760s", "word": "gato"},
        {"startOffset": "15.760s", "endOffset": "16.200s", "word": "deu."},
        {"startOffset": "16.280s", "endOffset": "17.880s", "word": "Miau."},
      ]),
    },
    "cravo": {
      "time": 21,
      "language": "pt-BR",
      "text": "O cravo brigou com a rosa\nDebaixo de uma sacada\nO cravo saiu ferido\nE a rosa, despedaçada",
      "words": process_words([
        {"startOffset": "1.240s", "endOffset": "1.680s", "word": "O"},
        {"startOffset": "1.680s", "endOffset": "2.800s", "word": "cravo"},
        {"startOffset": "2.800s", "endOffset": "3.560s", "word": "brigou"},
        {"startOffset": "3.560s", "endOffset": "3.760s", "word": "com"},
        {"startOffset": "3.760s", "endOffset": "3.920s", "word": "a"},
        {"startOffset": "3.920s", "endOffset": "5.080s", "word": "rosa,"},
        {"startOffset": "5.520s", "endOffset": "7.240s", "word": "debaixo"},
        {"startOffset": "7.240s", "endOffset": "7.400s", "word": "de"},
        {"startOffset": "7.400s", "endOffset": "7.920s", "word": "uma"},
        {"startOffset": "7.920s", "endOffset": "9.880s", "word": "sacada,"},
        {"startOffset": "10.040s", "endOffset": "10.560s", "word": "o"},
        {"startOffset": "10.560s", "endOffset": "11.680s", "word": "cravo"},
        {"startOffset": "11.680s", "endOffset": "12.440s", "word": "saiu"},
        {"startOffset": "12.440s", "endOffset": "14.400s", "word": "ferido"},
        {"startOffset": "14.440s", "endOffset": "14.640s", "word": "e"},
        {"startOffset": "14.640s", "endOffset": "15.120s", "word": "a"},
        {"startOffset": "15.120s", "endOffset": "16.240s", "word": "rosa"},
        {"startOffset": "16.240s", "endOffset": "18.960s", "word": "despedaçada."},
      ]),
    },
    "jingle": {
      "time": 7,
      "language": "en-US",
      "text": "Jingle bells, jingle bells\nJingle all the way\nOh what fun it is to ride\nIn a one horse open sleigh - hey!",
      "words": process_words([
        {"startOffset": "0s", "endOffset": "0.600s", "word": "Jingle"},
        {"startOffset": "0.600s", "endOffset": "1.200s", "word": "bells,"},
        {"startOffset": "1.200s", "endOffset": "1.720s", "word": "jingle"},
        {"startOffset": "1.720s", "endOffset": "2.320s", "word": "bells,"},
        {"startOffset": "2.320s", "endOffset": "3s", "word": "jingle"},
        {"startOffset": "3s", "endOffset": "3.320s", "word": "all"},
        {"startOffset": "3.320s", "endOffset": "3.520s", "word": "the"},
        {"startOffset": "3.520s", "endOffset": "3.720s", "word": "way."},
        {"startOffset": "4.720s", "endOffset": "4.760s", "word": "Oh,"},
        {"startOffset": "4.760s", "endOffset": "4.840s", "word": "what"},
        {"startOffset": "4.840s", "endOffset": "4.920s", "word": "fun"},
        {"startOffset": "4.920s", "endOffset": "4.960s", "word": "it"},
        {"startOffset": "4.960s", "endOffset": "5.040s", "word": "is"},
        {"startOffset": "5.040s", "endOffset": "5.080s", "word": "to"},
        {"startOffset": "5.080s", "endOffset": "5.200s", "word": "ride"},
        {"startOffset": "5.200s", "endOffset": "5.230s", "word": "in"},
        {"startOffset": "5.230s", "endOffset": "5.280s", "word": "a"},
        {"startOffset": "5.280s", "endOffset": "5.400s", "word": "one"},
        {"startOffset": "5.400s", "endOffset": "5.520s", "word": "horse"},
        {"startOffset": "5.520s", "endOffset": "5.680s", "word": "open"},
        {"startOffset": "5.680s", "endOffset": "5.760s", "word": "sleigh."},
        {"startOffset": "5.760s", "endOffset": "5.800s", "word": "Hey"},
      ]),
    },
    "old": {
      "time": 17,
      "language": "en-US",
      "text": "Old MacDonald had a farm\nE I E I O\nAnd on that farm he had a pig\nE I E I O\nWith an oink oink here\nAnd an oink oink there\nHere an oink there an oink\nEverywhere an oink oink",
      "words": process_words([
        {"startOffset": "0s", "endOffset": "0.360s", "word": "Old"},
        {"startOffset": "0.360s", "endOffset": "1.280s", "word": "MacDonald"},
        {"startOffset": "1.280s", "endOffset": "1.680s", "word": "had"},
        {"startOffset": "1.680s", "endOffset": "1.840s", "word": "a"},
        {"startOffset": "1.840s", "endOffset": "2.440s", "word": "farm."},
        {"startOffset": "2.560s", "endOffset": "2.960s", "word": "E"},
        {"startOffset": "2.960s", "endOffset": "3.160s", "word": "i"},
        {"startOffset": "3.160s", "endOffset": "3.480s", "word": "e"},
        {"startOffset": "3.480s", "endOffset": "3.800s", "word": "i"},
        {"startOffset": "3.800s", "endOffset": "4.280s", "word": "o."},
        {"startOffset": "4.720s", "endOffset": "5.080s", "word": "And"},
        {"startOffset": "5.080s", "endOffset": "5.320s", "word": "on"},
        {"startOffset": "5.320s", "endOffset": "5.640s", "word": "that"},
        {"startOffset": "5.640s", "endOffset": "6s", "word": "farm"},
        {"startOffset": "6s", "endOffset": "6.240s", "word": "he"},
        {"startOffset": "6.240s", "endOffset": "6.640s", "word": "had"},
        {"startOffset": "6.640s", "endOffset": "6.760s", "word": "a"},
        {"startOffset": "6.760s", "endOffset": "7.400s", "word": "pig."},
        {"startOffset": "7.560s", "endOffset": "7.960s", "word": "E"},
        {"startOffset": "7.960s", "endOffset": "8.240s", "word": "i"},
        {"startOffset": "8.240s", "endOffset": "8.560s", "word": "e"},
        {"startOffset": "8.560s", "endOffset": "8.880s", "word": "i"},
        {"startOffset": "8.880s", "endOffset": "9.360s", "word": "o."},
        {"startOffset": "9.680s", "endOffset": "9.880s", "word": "With"},
        {"startOffset": "9.880s", "endOffset": "10.040s", "word": "an"},
        {"startOffset": "10.040s", "endOffset": "10.360s", "word": "oink"},
        {"startOffset": "10.360s", "endOffset": "10.640s", "word": "oink"},
        {"startOffset": "10.640s", "endOffset": "10.960s", "word": "here"},
        {"startOffset": "10.960s", "endOffset": "11.120s", "word": "and"},
        {"startOffset": "11.120s", "endOffset": "11.280s", "word": "an"},
        {"startOffset": "11.280s", "endOffset": "11.600s", "word": "oink"},
        {"startOffset": "11.600s", "endOffset": "11.880s", "word": "oink"},
        {"startOffset": "11.880s", "endOffset": "12.320s", "word": "there."},
        {"startOffset": "12.480s", "endOffset": "12.680s", "word": "Here"},
        {"startOffset": "12.680s", "endOffset": "12.840s", "word": "an"},
        {"startOffset": "12.840s", "endOffset": "13.120s", "word": "oink"},
        {"startOffset": "13.120s", "endOffset": "13.360s", "word": "there"},
        {"startOffset": "13.360s", "endOffset": "13.480s", "word": "an"},
        {"startOffset": "13.480s", "endOffset": "13.800s", "word": "oink"},
        {"startOffset": "13.800s", "endOffset": "14.280s", "word": "everywhere"},
        {"startOffset": "14.280s", "endOffset": "14.400s", "word": "an"},
        {"startOffset": "14.400s", "endOffset": "14.720s", "word": "oink"},
        {"startOffset": "14.720s", "endOffset": "15s", "word": "oink"},
      ]),
    },
    "peixe": {
      "time": 20,
      "language": "pt-BR",
      "text": "Como pode um peixe vivo\nViver fora da água fria\nComo pode um peixe vivo\nViver fora da água fria\nComo poderei viver\nComo poderei viver\nSem a tua, sem a tua\nSem a tua companhia",
      "words": process_words([
        { "endOffset": "1.040s", "word": "Como", "confidence": 0.48399335 },
        {"startOffset": "1.040s", "endOffset": "1.520s", "word": "pode"},
        {"startOffset": "1.520s", "endOffset": "1.600s", "word": "um"},
        {"startOffset": "1.600s", "endOffset": "2.120s", "word": "peixe"},
        {"startOffset": "2.120s", "endOffset": "2.680s", "word": "vivo"},
        {"startOffset": "2.680s", "endOffset": "3.160s", "word": "viver"},
        {"startOffset": "3.160s", "endOffset": "3.720s", "word": "fora"},
        {"startOffset": "3.720s", "endOffset": "3.880s", "word": "da"},
        {"startOffset": "3.880s", "endOffset": "4.240s", "word": "água"},
        {"startOffset": "4.240s", "endOffset": "4.760s", "word": "fria?"},
        {"startOffset": "4.760s", "endOffset": "5.320s", "word": "Como"},
        {"startOffset": "5.320s", "endOffset": "5.760s", "word": "pode"},
        {"startOffset": "5.760s", "endOffset": "5.800s", "word": "um"},
        {"startOffset": "5.800s", "endOffset": "6.400s", "word": "peixe"},
        {"startOffset": "6.400s", "endOffset": "6.960s", "word": "vivo"},
        {"startOffset": "6.960s", "endOffset": "7.440s", "word": "viver"},
        {"startOffset": "7.440s", "endOffset": "8s", "word": "fora"},
        {"startOffset": "8s", "endOffset": "8.160s", "word": "da"},
        {"startOffset": "8.160s", "endOffset": "8.560s", "word": "água"},
        {"startOffset": "8.560s", "endOffset": "8.960s", "word": "fria?"},
        {"startOffset": "9.440s", "endOffset": "9.560s", "word": "Como"},
        {"startOffset": "10.080s", "endOffset": "10.560s", "word": "poderei"},
        {"startOffset": "10.560s", "endOffset": "11.360s", "word": "viver?"},
        {"startOffset": "11.560s", "endOffset": "11.800s", "word": "Como"},
        {"startOffset": "11.800s", "endOffset": "12.720s", "word": "poderei"},
        {"startOffset": "12.720s", "endOffset": "13.400s", "word": "viver?"},
        {"startOffset": "13.400s", "endOffset": "13.760s", "word": "Sem"},
        {"startOffset": "13.760s", "endOffset": "13.920s", "word": "a"},
        {"startOffset": "13.920s", "endOffset": "14.440s", "word": "tua,"},
        {"startOffset": "14.440s", "endOffset": "14.840s", "word": "sem"},
        {"startOffset": "14.840s", "endOffset": "14.960s", "word": "a"},
        {"startOffset": "14.960s", "endOffset": "15.520s", "word": "tua,"},
        {"startOffset": "15.520s", "endOffset": "15.880s", "word": "sem"},
        {"startOffset": "15.880s", "endOffset": "16.040s", "word": "a"},
        {"startOffset": "16.040s", "endOffset": "16.600s", "word": "tua"},
        {"startOffset": "16.600s", "endOffset": "17.560s", "word": "companhia."},
      ]),
    },
    "sapo": {
      "time": 10,
      "language": "pt-BR",
      "text": "Sapo cururu, na beira do rio\nQuando o sapo canta, maninha\nÉ porque tem frio",
      "words": process_words([
        {"startOffset": "0.320s", "endOffset": "0.840s", "word": "Sapo"},
        {"startOffset": "0.840s", "endOffset": "1.840s", "word": "cururu,"},
        {"startOffset": "2.600s", "endOffset": "3s", "word": "na"},
        {"startOffset": "3s", "endOffset": "3.440s", "word": "beira"},
        {"startOffset": "3.440s", "endOffset": "3.720s", "word": "do"},
        {"startOffset": "3.720s", "endOffset": "4.160s", "word": "rio,"},
        {"startOffset": "4.840s", "endOffset": "5.280s", "word": "quando"},
        {"startOffset": "5.280s", "endOffset": "5.320s", "word": "o"},
        {"startOffset": "5.480s", "endOffset": "6s", "word": "sapo"},
        {"startOffset": "6s", "endOffset": "6.440s", "word": "canta"},
        {"startOffset": "6.440s", "endOffset": "7.280s", "word": "maninha,"},
        {"startOffset": "7.280s", "endOffset": "7.400s", "word": "é"},
        {"startOffset": "7.400s", "endOffset": "8s", "word": "porque"},
        {"startOffset": "8s", "endOffset": "8.280s", "word": "tem"},
        {"startOffset": "8.280s", "endOffset": "8.800s", "word": "frio."},
      ]),
    },
    "spider": {
      "time": 17,
      "language": "en-US",
      "text": "Itsy-bitsy spider, went up the water spout\nDown came the rain and washed the spider out\nOut came the sunshine and dried up all the rain",
      "words": process_words([
        {"startOffset": "0.280s", "endOffset": "1.400s", "word": "Itsy-bitsy"},
        {"startOffset": "1.400s", "endOffset": "2.520s", "word": "spider"},
        {"startOffset": "2.520s", "endOffset": "2.840s", "word": "went"},
        {"startOffset": "2.840s", "endOffset": "3.160s", "word": "up"},
        {"startOffset": "3.160s", "endOffset": "3.400s", "word": "the"},
        {"startOffset": "3.400s", "endOffset": "3.960s", "word": "water"},
        {"startOffset": "3.960s", "endOffset": "4.680s", "word": "spout."},
        {"startOffset": "5.320s", "endOffset": "5.960s", "word": "Down"},
        {"startOffset": "5.960s", "endOffset": "6.400s", "word": "came"},
        {"startOffset": "6.400s", "endOffset": "6.600s", "word": "the"},
        {"startOffset": "6.600s", "endOffset": "7.240s", "word": "rain"},
        {"startOffset": "7.680s", "endOffset": "7.960s", "word": "and"},
        {"startOffset": "7.960s", "endOffset": "8.360s", "word": "washed"},
        {"startOffset": "8.360s", "endOffset": "8.480s", "word": "the"},
        {"startOffset": "8.480s", "endOffset": "9.320s", "word": "spider"},
        {"startOffset": "9.320s", "endOffset": "9.920s", "word": "out."},
        {"startOffset": "10.640s", "endOffset": "11.120s", "word": "Out"},
        {"startOffset": "11.120s", "endOffset": "11.560s", "word": "came"},
        {"startOffset": "11.560s", "endOffset": "11.720s", "word": "the"},
        {"startOffset": "11.720s", "endOffset": "12.880s", "word": "sunshine"},
        {"startOffset": "12.880s", "endOffset": "13.040s", "word": "and"},
        {"startOffset": "13.040s", "endOffset": "13.520s", "word": "dried"},
        {"startOffset": "13.520s", "endOffset": "13.760s", "word": "up"},
        {"startOffset": "13.760s", "endOffset": "14.080s", "word": "all"},
        {"startOffset": "14.080s", "endOffset": "14.320s", "word": "the"},
        {"startOffset": "14.320s", "endOffset": "15.200s", "word": "rain."},
      ]),
    },
    "wish": {
      "time": 13,
      "language": "en-US",
      "text": "We wish you a Merry Christmas\nWe wish you a Merry Christmas\nWe wish you a Merry Christmas\nAnd a happy new year",
      "words": process_words([
        {"startOffset": "0.640s", "endOffset": "1.080s", "word": "We"},
        {"startOffset": "1.080s", "endOffset": "1.560s", "word": "wish"},
        {"startOffset": "1.560s", "endOffset": "1.800s", "word": "you"},
        {"startOffset": "1.800s", "endOffset": "1.920s", "word": "a"},
        {"startOffset": "1.920s", "endOffset": "2.360s", "word": "Merry"},
        {"startOffset": "2.360s", "endOffset": "3.280s", "word": "Christmas."},
        {"startOffset": "3.280s", "endOffset": "3.680s", "word": "We"},
        {"startOffset": "3.680s", "endOffset": "4.160s", "word": "wish"},
        {"startOffset": "4.160s", "endOffset": "4.360s", "word": "you"},
        {"startOffset": "4.360s", "endOffset": "4.520s", "word": "a"},
        {"startOffset": "4.520s", "endOffset": "4.960s", "word": "Merry"},
        {"startOffset": "4.960s", "endOffset": "5.840s", "word": "Christmas."},
        {"startOffset": "5.880s", "endOffset": "6.280s", "word": "We"},
        {"startOffset": "6.280s", "endOffset": "6.760s", "word": "wish"},
        {"startOffset": "6.760s", "endOffset": "7s", "word": "you"},
        {"startOffset": "7s", "endOffset": "7.120s", "word": "a"},
        {"startOffset": "7.120s", "endOffset": "7.520s", "word": "Merry"},
        {"startOffset": "7.520s", "endOffset": "8.440s", "word": "Christmas"},
        {"startOffset": "8.480s", "endOffset": "8.760s", "word": "and"},
        {"startOffset": "8.760s", "endOffset": "8.880s", "word": "a"},
        {"startOffset": "8.880s", "endOffset": "9.680s", "word": "happy"},
        {"startOffset": "9.680s", "endOffset": "10.120s", "word": "new"},
        {"startOffset": "10.120s", "endOffset": "11s", "word": "year."},
      ]),
    },
}
